from typing import Iterator, Protocol

from pyodide import JsProxy

class Window(Protocol):
    def requestAnimationFrame(self, callback: JsProxy) -> None: ...

class Storage(Protocol):
    def setItem(self, key: str, value: str) -> None: ...
    def getItem(self, key: str) -> str | None: ...
    def removeItem(self, key: str) -> None: ...
    def object_keys(self) -> Iterator[str]: ...
    @property
    def length(self) -> int: ...

class CSSSTyleDeclaratin(Protocol): ...

class HTMLElement(Protocol):
    def appendChild(self, child: HTMLElement) -> None: ...
    def insertBefore(
        self, child: HTMLElement, reference: HTMLElement | None = ...
    ) -> None: ...
    def removeChild(self, child: HTMLElement) -> None: ...
    def addEventListener(self, event_type: str, listener: JsProxy) -> None: ...
    def removeEventListener(self, event_type: str, listener: JsProxy) -> None: ...
    def setAttribute(self, name: str, value: str) -> None: ...
    def removeAttribute(self, name: str) -> None: ...
    def focus(self) -> None: ...
    @property
    def style(self) -> CSSSTyleDeclaratin: ...
    @property
    def nodeValue(self) -> str: ...
    @nodeValue.setter
    def nodeValue(self, text: str) -> None: ...

class Text(HTMLElement): ...

class Location(Protocol):
    def assign(self, url: str) -> None: ...
    def reload(self) -> None: ...
    def replace(self, url: str) -> None: ...

class HTMLDocument(Protocol):
    def createTextNode(self, text: str) -> Text: ...
    def createElement(self, tag: str, props: JsProxy) -> HTMLElement: ...
    def getElementById(self, id: str) -> HTMLElement: ...
    def addEventListener(self, event_type: str, listener: JsProxy) -> None: ...
    def removeEventListener(self, event_type: str, listener: JsProxy) -> None: ...
    @property
    def location(self) -> Location: ...

document: HTMLDocument
location: Location
localStorage: Storage
window: Window
