# derived from https://github.com/pyodide/pyodide/blob/main/src/py/pyodide/http.py

from io import StringIO
from typing import Any, BinaryIO, TextIO

from .. import JsProxy

def open_url(url: str) -> StringIO: ...

class FetchResponse:
    def __init__(self, url: str, js_response: JsProxy) -> None: ...
    @property
    def body_used(self) -> bool: ...
    @property
    def ok(self) -> bool: ...
    @property
    def redirected(self) -> bool: ...
    @property
    def status(self) -> str: ...
    @property
    def status_text(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def url(self) -> str: ...
    def clone(self) -> "FetchResponse": ...
    async def buffer(self) -> JsProxy: ...
    async def string(self) -> str: ...
    async def json(self, **kwargs: Any) -> Any: ...
    async def memoryview(self) -> memoryview: ...
    async def bytes(self) -> bytes: ...
    async def _into_file(self, f: TextIO | BinaryIO) -> None: ...
    async def unpack_archive(
        self, *, extract_dir: str | None, format: str | None
    ) -> None: ...

async def pyfetch(url: str, **kwargs: Any) -> FetchResponse: ...
